# Merge

In [1]:
import pandas as pd

In [2]:
var1 = pd.DataFrame({"A":[1,2,3,4,5] , "B":[11,12,13,14,15]})
var2 = pd.DataFrame({"A":[1,2,3,4,5] , "C":[21,22,23,24,25]})
pd.merge(var1,var2,)

A   B   C
0  1  11  21
1  2  12  22
2  3  13  23
3  4  14  24
4  5  15  25

In [3]:
pd.merge(var1,var2,on = "A")

A   B   C
0  1  11  21
1  2  12  22
2  3  13  23
3  4  14  24
4  5  15  25

In [4]:
var3 = pd.DataFrame({"A":[1,2,3,4,5] , "B":[11,12,13,14,15]})
var4 = pd.DataFrame({"A":[1,2,3,4,6] , "C":[21,22,23,24,25]})
pd.merge(var3,var4)

A   B   C
0  1  11  21
1  2  12  22
2  3  13  23
3  4  14  24

In [5]:
pd.merge(var3,var4,on = "A")

A   B   C
0  1  11  21
1  2  12  22
2  3  13  23
3  4  14  24

In [6]:
pd.merge(var3,var4, how = "left")

A   B     C
0  1  11  21.0
1  2  12  22.0
2  3  13  23.0
3  4  14  24.0
4  5  15   NaN

In [7]:
pd.merge(var3,var4, how = "right")

A     B   C
0  1  11.0  21
1  2  12.0  22
2  3  13.0  23
3  4  14.0  24
4  6   NaN  25

In [8]:
pd.merge(var3,var4, how = "outer")

A     B     C
0  1  11.0  21.0
1  2  12.0  22.0
2  3  13.0  23.0
3  4  14.0  24.0
4  5  15.0   NaN
5  6   NaN  25.0

In [9]:
pd.merge(var3,var4, how = "outer" , indicator = True)

A     B     C      _merge
0  1  11.0  21.0        both
1  2  12.0  22.0        both
2  3  13.0  23.0        both
3  4  14.0  24.0        both
4  5  15.0   NaN   left_only
5  6   NaN  25.0  right_only

In [10]:
var5 = pd.DataFrame({"A":[1,2,3,4,5] , "B":[11,12,13,14,15]})
var6 = pd.DataFrame({"A":[1,2,3,4,6] , "B":[21,22,23,24,25]})
pd.merge(var5,var6 , left_index = True , right_index = True)

A_x  B_x  A_y  B_y
0    1   11    1   21
1    2   12    2   22
2    3   13    3   23
3    4   14    4   24
4    5   15    6   25

In [11]:
#To change a name of COLUMN then we use "suffixes"

In [12]:
pd.merge(var5,var6 , left_index = True , right_index = True , suffixes = ("_ID" , "_NAME"))

A_ID  B_ID  A_NAME  B_NAME
0     1    11       1      21
1     2    12       2      22
2     3    13       3      23
3     4    14       4      24
4     5    15       6      25

# Concat

In [13]:
import pandas as pd

In [14]:
Series1 = pd.Series([1,2,3,4,5])
Series2 = pd.Series([6,7,8,9,10])
pd.concat([Series1,Series2])

0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
3     9
4    10
dtype: int64

In [15]:
df1 = pd.DataFrame({"A":[1,2,3,4,5] , "B":[11,12,13,14,15]})
df2 = pd.DataFrame({"A":[1,2,3,4,6] , "B":[21,22,23,24,25]})
pd.concat([df1,df2])

A   B
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15
0  1  21
1  2  22
2  3  23
3  4  24
4  6  25

In [16]:
pd.concat([df1,df2],axis = 1)

A   B  A   B
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  14  4  24
4  5  15  6  25

In [17]:
df3 = pd.DataFrame({"A":[1,2,3,4,5] , "B":[11,12,13,14,15]})
df4 = pd.DataFrame({"A":[1,2,3,4,6] , "B":[21,22,23,24,25]})
pd.concat([df3,df4], axis =1)

A   B  A   B
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  14  4  24
4  5  15  6  25

# 08.02.2024 

In [18]:
import pandas as pd
import numpy as np

In [19]:
def add(num1,num2):
    sum = num1  * num2
    print(sum)
    
add(5,6)

30


In [20]:
range(5)[3]

3

In [21]:
Starvalue = range(5)[3]
print("The frst element in range is = " , Starvalue)

The frst element in range is =  3


In [22]:
for i in range(3,10,2):
    print(i)

3
5
7
9


In [23]:
for i in range(3,10,2):
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [24]:
for i in range(3,10,2):
    print(list(range(5)))

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]


In [25]:
#Range works for "String" only

In [26]:
print(ord('A'))

65


In [27]:
#generator function
def get_alphabets(Startletter,Stopletter,Step):
    for c in range(ord(Startletter.lower()),ord(Stopletter.lower()),Step):
        yield chr(c)
    
print(list(get_alphabets("A" , "H" , 1)))

['a', 'b', 'c', 'd', 'e', 'f', 'g']


In [28]:
#user defined function
def alphabets(letter1,letter2):
    print(letter1)
    print(letter2)
    
alphabets("a","b")

a
b


# 13.02.2024 

# Series :- A series in pandas is one dimensional labeled array capable of holding any data type (Tuple,List,String,Float,Int).The label are collectively called index.A collection of series in a tabular form is called DataFrame in pandas.Reversely a series can be considered as 1 column of a DataFrame.  

In [29]:
import pandas as pd

In [30]:
List1 = [1,2,3,4,5,6,7,8,9,10]
print(type(List1))

<class 'list'>


In [31]:
Series = pd.Series(List1)
print(Series)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64


In [138]:
Series1 = pd.Series([1,"John",3.5,"False"])
x = pd.Series([1,"John",3.5,"False"])
print(x)

0        1
1     John
2      3.5
3    False
dtype: object


In [139]:
print(Series1[3])

False


In [140]:
Series1[3]

'False'

In [35]:
List1 = [1,2,3,4,5,6,7,8,9,10]
List1[3]

4

# Alterations in indexing

In [36]:
Series2 = pd.Series([1,"John",3.5,"False"],index = ["A","B","C","D"])
print(Series2)

A        1
B     John
C      3.5
D    False
dtype: object


In [37]:
Series3 = pd.Series([1,"John",3.5,"False"],index = [10,11,12,13])
print(Series3)

10        1
11     John
12      3.5
13    False
dtype: object


In [38]:
Dict1 = pd.Series({"Rishabh":11,"Raju":23,"Swara":88,"Siddyyy": 76})
print(Dict1)

Rishabh    11
Raju       23
Swara      88
Siddyyy    76
dtype: int64


In [142]:
Name = pd.Series({"Jane":90,"Billy":80,"Elon":85,"Tom": 75,"Timoth":95})
print(Name[4])

95


In [144]:
Name = pd.Series({"Jane":90,"Billy":80,"Elon":85,"Tom": 75,"Timoth":95})
Name["Tom"]=60
print(Name)

Jane      90
Billy     80
Elon      85
Tom       60
Timoth    95
dtype: int64


# 15.02.2024

In [41]:
#1
color = ["Red","Blue","Yellow","Pink","Black"]
color.append("Purple")
print(color) 

['Red', 'Blue', 'Yellow', 'Pink', 'Black', 'Purple']


In [42]:
#2
L1 = [1,2,3]
L2 = [4,5,6]
L1.extend(L2) 
print(L1)

[1, 2, 3, 4, 5, 6]


In [43]:
#3
List1 = ["Cat","Dog","Rabbit","Lion"]
List1.insert(1,"Tiger") 
print(List1)

['Cat', 'Tiger', 'Dog', 'Rabbit', 'Lion']


In [44]:
#4
List2 = [1,2,3,4,5]
List2.remove(5) 
print(List2)

[1, 2, 3, 4]


In [45]:
#5
List3 = [1,2,3,4,5]
List3.pop(2) 
print(List3)

[1, 2, 4, 5]


In [46]:
#6(ascendingorder)
List4 = [4,3,7,2,7,3,8,2,7,4]
List4.sort() 
print(List4)

[2, 2, 3, 3, 4, 4, 7, 7, 7, 8]


In [47]:
#max7
List5 = [23,44,12,54,23]
print(max(List5)) 

54


In [48]:
#min7
List5 = [23,44,12,54,23]
print(min(List5)) 

12


In [49]:
#8
List6 = [1,2,3,3,3,4,5,6]
print(List6.index(3))

2


In [50]:
#9
List7 = [1,2,3,4,5]
List7.remove(2)
print(List7) 

[1, 3, 4, 5]


In [51]:
#10
List8 = [5,4,3,2,1]
List8.reverse() 
print(List8)

[1, 2, 3, 4, 5]


In [52]:
#11
List9 = [1,2,3,4,5]
new = List9.copy()
print(List9) 
print(new)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [53]:
#11
List9 = [1,2,3,4,5]
print(List9.copy()) 

[1, 2, 3, 4, 5]


In [54]:
#12
List10 = [1,2,3,4,5]
List10.clear() 
print(List10)

[]


In [55]:
 #13
List11 = [1,1,2,2,2,3,3,4,5,6,6]
print(List11.count(2))

3


# Data Frame

In [145]:
import pandas as pd

In [156]:
df = {"Name":["Bill","Tom","Tim","John","Alex","Vanessa","Kate"],
       "Score":[90,80,85,75,95,60,65],
       "Sport":["Wrestling","Football","Skiing","Swimming","Tennis","Karete","Surfing"],
       "Sex":["M","M","M","M","M","F","F"]}
print(df)

{'Name': ['Bill', 'Tom', 'Tim', 'John', 'Alex', 'Vanessa', 'Kate'], 'Score': [90, 80, 85, 75, 95, 60, 65], 'Sport': ['Wrestling', 'Football', 'Skiing', 'Swimming', 'Tennis', 'Karete', 'Surfing'], 'Sex': ['M', 'M', 'M', 'M', 'M', 'F', 'F']}


In [157]:
df = pd.DataFrame(df,columns =["Name","Sex","Sport","Score","Gender"])
df

Name Sex      Sport  Score Gender
0     Bill   M  Wrestling     90    NaN
1      Tom   M   Football     80    NaN
2      Tim   M     Skiing     85    NaN
3     John   M   Swimming     75    NaN
4     Alex   M     Tennis     95    NaN
5  Vanessa   F     Karete     60    NaN
6     Kate   F    Surfing     65    NaN

In [5]:
df = pd.DataFrame(df,columns = ["Name","Sex","Sport","Score"])
df["Gender"] = df["Sex"].map ({"M":"Male","F":"Female"})
print(df)

      Name Sex      Sport  Score  Gender
0     Bill   M  Wrestling     90    Male
1      Tom   M   Football     80    Male
2      Tim   M     Skiing     85    Male
3     John   M   Swimming     75    Male
4     Alex   M     Tennis     95    Male
5  Vanessa   F     Karete     60  Female
6     Kate   F    Surfing     65  Female


In [6]:
df["num_gender"] = df["Gender"].map({"Male":1,"Female":0})
print(df)

      Name Sex      Sport  Score  Gender  num_gender
0     Bill   M  Wrestling     90    Male           1
1      Tom   M   Football     80    Male           1
2      Tim   M     Skiing     85    Male           1
3     John   M   Swimming     75    Male           1
4     Alex   M     Tennis     95    Male           1
5  Vanessa   F     Karete     60  Female           0
6     Kate   F    Surfing     65  Female           0


In [7]:
df.drop(["Sex"],inplace = True ,axis = 1)
df

Name      Sport  Score  Gender  num_gender
0     Bill  Wrestling     90    Male           1
1      Tom   Football     80    Male           1
2      Tim     Skiing     85    Male           1
3     John   Swimming     75    Male           1
4     Alex     Tennis     95    Male           1
5  Vanessa     Karete     60  Female           0
6     Kate    Surfing     65  Female           0

# 16.02.2024

In [ ]:
import pandas as pd

In [ ]:
#2 Print the DataFrame scores df to display the students' exam scores in Math and Physics.Ensure that the row and column labels are appropriately named
scores ={"Math":{"Swara":85,"Siddharth":90,"Nakul":66,"Khushi":61,"Harshyyy":77},
        "Physics":{"Swara":65,"Siddharth":45,"Nakul":68,"Khushi":51,"Harshyyy":79}}
scores_df = pd.DataFrame(scores)
scores_df.index.name = "Name"
scores_df.columns.name = "lesson"
print(scores_df)

# 20.02.2024

In [8]:
#Location Finder 

In [1]:
import pandas as pd

In [10]:
df = pd.DataFrame({"A":[1,2,3],"B":[4,5,6]},index = ["Row1","Row2","Row3"])
df                 

A  B
Row1  1  4
Row2  2  5
Row3  3  6

In [11]:
df.loc["Row2","B"]

5

In [12]:
df.iloc[1,1]

5

In [14]:
df = pd.DataFrame({"Weight":[45,88,56,15,71],
                  "Name":["Sam","Andrea","Alex","Robin","Kia"],
                  "Age":[14,25,55,8,21]})
index_ = ["Row_1","Row_2","Row_3","Row_4","Row_5"]
df

Weight    Name  Age
0      45     Sam   14
1      88  Andrea   25
2      56    Alex   55
3      15   Robin    8
4      71     Kia   21

In [15]:
df.index = index_
df

Weight    Name  Age
Row_1      45     Sam   14
Row_2      88  Andrea   25
Row_3      56    Alex   55
Row_4      15   Robin    8
Row_5      71     Kia   21

In [16]:
print("Original DataFrame:")
print(df)

Original DataFrame:
       Weight    Name  Age
Row_1      45     Sam   14
Row_2      88  Andrea   25
Row_3      56    Alex   55
Row_4      15   Robin    8
Row_5      71     Kia   21


In [21]:
df.loc["Row_1"]

Weight     45
Name      Sam
Age        14
Name: Row_1, dtype: object

In [18]:
df.iloc[0]

Weight     45
Name      Sam
Age        14
Name: Row_1, dtype: object

In [18]:
df.loc[:,"Name"] 

Row_1       Sam
Row_2    Andrea
Row_3      Alex
Row_4     Robin
Row_5       Kia
Name: Name, dtype: object

In [19]:
df.iloc[:,1]

Row_1       Sam
Row_2    Andrea
Row_3      Alex
Row_4     Robin
Row_5       Kia
Name: Name, dtype: object

In [20]:
df = pd.DataFrame({"A":[12,4,5,None,1],
                  "B":[7,2,54,3,None],
                  "C":[20,16,11,3,8],
                  "D":[14,3,None,2,6]})
index_ = ["Row_1","Row_2","Row_3","Row_4","Row_5"]
df

A     B   C     D
0  12.0   7.0  20  14.0
1   4.0   2.0  16   3.0
2   5.0  54.0  11   NaN
3   NaN   3.0   3   2.0
4   1.0   NaN   8   6.0

In [21]:
df.index = index_
df

A     B   C     D
Row_1  12.0   7.0  20  14.0
Row_2   4.0   2.0  16   3.0
Row_3   5.0  54.0  11   NaN
Row_4   NaN   3.0   3   2.0
Row_5   1.0   NaN   8   6.0

In [22]:
df.loc[:,"B":"D"]

B   C     D
Row_1   7.0  20  14.0
Row_2   2.0  16   3.0
Row_3  54.0  11   NaN
Row_4   3.0   3   2.0
Row_5   NaN   8   6.0

In [23]:
df.iloc[:,1:4]

B   C     D
Row_1   7.0  20  14.0
Row_2   2.0  16   3.0
Row_3  54.0  11   NaN
Row_4   3.0   3   2.0
Row_5   NaN   8   6.0

In [24]:
df.iloc[:,1::2]

B     D
Row_1   7.0  14.0
Row_2   2.0   3.0
Row_3  54.0   NaN
Row_4   3.0   2.0
Row_5   NaN   6.0

# HOMEWORK
Creating a DataFrame containing 5 Rows and 15 Coumns.
Print the columns alternatively
Part 1 = Leaving 1 column between
Part 2 = Leaving 2 column between

# 23.02.2024

In [25]:
import pandas as pd

In [26]:
df = pd.DataFrame({"A":[12,4,5,None,1],
                  "B":[7,2,54,3,None],
                  "C":[20,16,11,3,8],
                  "D":[14,3,None,2,6],
                  "E":[23,44,1,None,4],
                  "F":[87,11,None,33,2],
                  "G":[11,3,43,22,None],
                  "H":[33,7,33,51,None],
                  "I":[None,9,8,44,53],
                  "J":[22,54,33,None,22],
                  "K":[11,27,43,77,None],
                  "L":[22,4,26,44,None],
                  "M":[None,None,44,12,22],
                  "N":[23,44,12,None,11],
                  "O":[11,12,12,None,66]})
index_ = ["Row_1","Row_2","Row_3","Row_4","Row_5"]
df

A     B   C     D     E     F     G     H     I     J     K     L     M  \
0  12.0   7.0  20  14.0  23.0  87.0  11.0  33.0   NaN  22.0  11.0  22.0   NaN   
1   4.0   2.0  16   3.0  44.0  11.0   3.0   7.0   9.0  54.0  27.0   4.0   NaN   
2   5.0  54.0  11   NaN   1.0   NaN  43.0  33.0   8.0  33.0  43.0  26.0  44.0   
3   NaN   3.0   3   2.0   NaN  33.0  22.0  51.0  44.0   NaN  77.0  44.0  12.0   
4   1.0   NaN   8   6.0   4.0   2.0   NaN   NaN  53.0  22.0   NaN   NaN  22.0   

      N     O  
0  23.0  11.0  
1  44.0  12.0  
2  12.0  12.0  
3   NaN   NaN  
4  11.0  66.0

In [27]:
df.index = index_
df

A     B   C     D     E     F     G     H     I     J     K     L  \
Row_1  12.0   7.0  20  14.0  23.0  87.0  11.0  33.0   NaN  22.0  11.0  22.0   
Row_2   4.0   2.0  16   3.0  44.0  11.0   3.0   7.0   9.0  54.0  27.0   4.0   
Row_3   5.0  54.0  11   NaN   1.0   NaN  43.0  33.0   8.0  33.0  43.0  26.0   
Row_4   NaN   3.0   3   2.0   NaN  33.0  22.0  51.0  44.0   NaN  77.0  44.0   
Row_5   1.0   NaN   8   6.0   4.0   2.0   NaN   NaN  53.0  22.0   NaN   NaN   

          M     N     O  
Row_1   NaN  23.0  11.0  
Row_2   NaN  44.0  12.0  
Row_3  44.0  12.0  12.0  
Row_4  12.0   NaN   NaN  
Row_5  22.0  11.0  66.0

In [28]:
df.iloc[:,0::2]

A   C     E     G     I     K     M     O
Row_1  12.0  20  23.0  11.0   NaN  11.0   NaN  11.0
Row_2   4.0  16  44.0   3.0   9.0  27.0   NaN  12.0
Row_3   5.0  11   1.0  43.0   8.0  43.0  44.0  12.0
Row_4   NaN   3   NaN  22.0  44.0  77.0  12.0   NaN
Row_5   1.0   8   4.0   NaN  53.0   NaN  22.0  66.0

In [29]:
selected_rows = df.loc[df["A"]>4]
print("\nRows where colums 'A' is greater than 5:")
print(selected_rows)


Rows where colums 'A' is greater than 5:
          A     B   C     D     E     F     G     H    I     J     K     L  \
Row_1  12.0   7.0  20  14.0  23.0  87.0  11.0  33.0  NaN  22.0  11.0  22.0   
Row_3   5.0  54.0  11   NaN   1.0   NaN  43.0  33.0  8.0  33.0  43.0  26.0   

          M     N     O  
Row_1   NaN  23.0  11.0  
Row_3  44.0  12.0  12.0  


In [30]:
Data =            ({"A":[12,4,5,None,1],
                  "B":[7,2,54,3,None],
                  "C":[20,16,11,3,8],
                  "D":[14,3,None,2,6],
                  "E":[23,44,1,None,4],
                  "F":[87,11,None,33,2],
                  "G":[11,3,43,22,None],
                  "H":[33,7,33,51,None],
                  "I":[None,9,8,44,53],
                  "J":[22,54,33,None,22],
                  "K":[11,27,43,77,None],
                  "L":[22,4,26,44,None],
                  "M":[None,None,44,12,22],
                  "N":[23,44,12,None,11],
                  "O":[11,12,12,None,66]})
df = pd.DataFrame(Data)
print(df)

      A     B   C     D     E     F     G     H     I     J     K     L     M  \
0  12.0   7.0  20  14.0  23.0  87.0  11.0  33.0   NaN  22.0  11.0  22.0   NaN   
1   4.0   2.0  16   3.0  44.0  11.0   3.0   7.0   9.0  54.0  27.0   4.0   NaN   
2   5.0  54.0  11   NaN   1.0   NaN  43.0  33.0   8.0  33.0  43.0  26.0  44.0   
3   NaN   3.0   3   2.0   NaN  33.0  22.0  51.0  44.0   NaN  77.0  44.0  12.0   
4   1.0   NaN   8   6.0   4.0   2.0   NaN   NaN  53.0  22.0   NaN   NaN  22.0   

      N     O  
0  23.0  11.0  
1  44.0  12.0  
2  12.0  12.0  
3   NaN   NaN  
4  11.0  66.0  


In [31]:
import pandas as pd

In [32]:
df = pd.read_csv('nba.csv')
df

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  
457                NaN        NaN  

[458 rows x 9 columns]

In [33]:
df.head(6)

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
5   Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0   

             College      Salary  
0              Texas   7730337.0  
1          Marquette   6796117.0  
2  Boston University         NaN  
3      Georgia State   1148640.0  
4                NaN   5000000.0  
5                NaN  12000000.0

In [34]:
df.tail(4)

Name       Team  Number Position   Age Height  Weight College  \
454     Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN   
455  Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN   
456   Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas   
457           NaN        NaN     NaN      NaN   NaN    NaN     NaN     NaN   

        Salary  
454   900000.0  
455  2900000.0  
456   947276.0  
457        NaN

In [35]:
Name = df["Name"]
Name

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...      
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: object

In [36]:
df["Name"]

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...      
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: object

In [37]:
Name.tail(10)

448    Gordon Hayward
449       Rodney Hood
450        Joe Ingles
451     Chris Johnson
452        Trey Lyles
453      Shelvin Mack
454         Raul Neto
455      Tibor Pleiss
456       Jeff Withey
457               NaN
Name: Name, dtype: object

In [38]:
df.describe()

Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [39]:
Weight = df["Weight"]
Weight

0      180.0
1      235.0
2      205.0
3      185.0
4      231.0
       ...  
453    203.0
454    179.0
455    256.0
456    231.0
457      NaN
Name: Weight, Length: 458, dtype: float64

In [40]:
df.describe()

Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [41]:
College = df["College"]
College

0                  Texas
1              Marquette
2      Boston University
3          Georgia State
4                    NaN
             ...        
453               Butler
454                  NaN
455                  NaN
456               Kansas
457                  NaN
Name: College, Length: 458, dtype: object

In [42]:
df.drop(["College"],axis=1)

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

        Salary  
0    7730337.0  
1    6796117.0  
2          NaN  
3    1148640.0  
4    5000000.0  
..         ...  
453  2433333.0  
454   900000.0  
455  2900000.0  
456   947276.0  
457        NaN  

[458 rows x 8 columns]

In [43]:
df.drop(0)

Name            Team  Number Position   Age Height  Weight  \
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
5     Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College      Salary  
1            Marquette   6796117.0  
2    Boston University         NaN  
3        Georgia State   1148640.0  
4                  NaN   5000000.0  
5                  NaN  12000000.0  
..                 ...         ...  
453             Butler   2433333.0  
454                NaN    900000.0  
455                NaN   2900000.0  
456             Kansas    947276.0  
457                NaN         NaN  

[457 rows x 9 columns]

In [44]:
df = pd.read_csv('nba.csv',index_col ='Name')
df

Team  Number Position   Age Height  Weight  \
Name                                                                  
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0   
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0   
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0   
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
...                       ...     ...      ...   ...    ...     ...   
Shelvin Mack        Utah Jazz     8.0       PG  26.0    6-3   203.0   
Raul Neto           Utah Jazz    25.0       PG  24.0    6-1   179.0   
Tibor Pleiss        Utah Jazz    21.0        C  26.0    7-3   256.0   
Jeff Withey         Utah Jazz    24.0        C  26.0    7-0   231.0   
NaN                       NaN     NaN      NaN   NaN    NaN     NaN   

                         College     Salary  
Name                                         
Avery Bradley              Texas  7730337.0  
Jae Crowder            Marquette  6796117.0  
John Holland   Boston University        NaN  
R.J. Hunter        Georgia State  1148640.0  
Jonas Jerebko                NaN  5000000.0  
...                          ...        ...  
Shelvin Mack              Butler  2433333.0  
Raul Neto                    NaN   900000.0  
Tibor Pleiss                 NaN  2900000.0  
Jeff Withey               Kansas   947276.0  
NaN                          NaN        NaN  

[458 rows x 8 columns]

In [45]:
df.drop(["Avery Bradley"])

Team  Number Position   Age Height  Weight  \
Name                                                                  
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0   
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0   
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0   
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
Amir Johnson   Boston Celtics    90.0       PF  29.0    6-9   240.0   
...                       ...     ...      ...   ...    ...     ...   
Shelvin Mack        Utah Jazz     8.0       PG  26.0    6-3   203.0   
Raul Neto           Utah Jazz    25.0       PG  24.0    6-1   179.0   
Tibor Pleiss        Utah Jazz    21.0        C  26.0    7-3   256.0   
Jeff Withey         Utah Jazz    24.0        C  26.0    7-0   231.0   
NaN                       NaN     NaN      NaN   NaN    NaN     NaN   

                         College      Salary  
Name                                          
Jae Crowder            Marquette   6796117.0  
John Holland   Boston University         NaN  
R.J. Hunter        Georgia State   1148640.0  
Jonas Jerebko                NaN   5000000.0  
Amir Johnson                 NaN  12000000.0  
...                          ...         ...  
Shelvin Mack              Butler   2433333.0  
Raul Neto                    NaN    900000.0  
Tibor Pleiss                 NaN   2900000.0  
Jeff Withey               Kansas    947276.0  
NaN                          NaN         NaN  

[457 rows x 8 columns]

In [46]:
#After creating index can we delete columns

In [47]:
#Sorting Values 
#Syntax:DataFrame.sort_values(by,axis=0,ascending=True,inplace=False,Kind='quicksort',na_position='last')

In [48]:
import pandas as pd

In [49]:
df = pd.read_csv('nba.csv',index_col ='Name')
df

Team  Number Position   Age Height  Weight  \
Name                                                                  
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0   
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0   
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0   
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
...                       ...     ...      ...   ...    ...     ...   
Shelvin Mack        Utah Jazz     8.0       PG  26.0    6-3   203.0   
Raul Neto           Utah Jazz    25.0       PG  24.0    6-1   179.0   
Tibor Pleiss        Utah Jazz    21.0        C  26.0    7-3   256.0   
Jeff Withey         Utah Jazz    24.0        C  26.0    7-0   231.0   
NaN                       NaN     NaN      NaN   NaN    NaN     NaN   

                         College     Salary  
Name                                         
Avery Bradley              Texas  7730337.0  
Jae Crowder            Marquette  6796117.0  
John Holland   Boston University        NaN  
R.J. Hunter        Georgia State  1148640.0  
Jonas Jerebko                NaN  5000000.0  
...                          ...        ...  
Shelvin Mack              Butler  2433333.0  
Raul Neto                    NaN   900000.0  
Tibor Pleiss                 NaN  2900000.0  
Jeff Withey               Kansas   947276.0  
NaN                          NaN        NaN  

[458 rows x 8 columns]

In [50]:
#Sort the data set with respect to the names keeping the null values at the bottom of the wrist

In [51]:
df.sort_values('Name',axis=0,ascending=True,inplace =True,na_position='first')
df

Team  Number Position   Age Height  Weight  \
Name                                                                            
NaN                                 NaN     NaN      NaN   NaN    NaN     NaN   
Aaron Brooks              Chicago Bulls     0.0       PG  31.0    6-0   161.0   
Aaron Gordon              Orlando Magic     0.0       PF  20.0    6-9   220.0   
Aaron Harrison        Charlotte Hornets     9.0       SG  21.0    6-6   210.0   
Adreian Payne    Minnesota Timberwolves    33.0       PF  25.0   6-10   237.0   
...                                 ...     ...      ...   ...    ...     ...   
Wilson Chandler          Denver Nuggets    21.0       SF  29.0    6-8   225.0   
Xavier Munford        Memphis Grizzlies    14.0       PG  24.0    6-3   180.0   
Zach LaVine      Minnesota Timberwolves     8.0       PG  21.0    6-5   189.0   
Zach Randolph         Memphis Grizzlies    50.0       PF  34.0    6-9   260.0   
Zaza Pachulia          Dallas Mavericks    27.0        C  32.0   6-11   275.0   

                        College      Salary  
Name                                         
NaN                         NaN         NaN  
Aaron Brooks             Oregon   2250000.0  
Aaron Gordon            Arizona   4171680.0  
Aaron Harrison         Kentucky    525093.0  
Adreian Payne    Michigan State   1938840.0  
...                         ...         ...  
Wilson Chandler          DePaul  10449438.0  
Xavier Munford     Rhode Island         NaN  
Zach LaVine                UCLA   2148360.0  
Zach Randolph    Michigan State   9638555.0  
Zaza Pachulia               NaN   5200000.0  

[458 rows x 8 columns]

In [52]:
df.sort_values('Age',axis=0,ascending=True,inplace =True,na_position='first')
df

Team  Number Position   Age Height  Weight  \
Name                                                                            
NaN                                 NaN     NaN      NaN   NaN    NaN     NaN   
Rashad Vaughn           Milwaukee Bucks    20.0       SG  19.0    6-6   202.0   
Devin Booker               Phoenix Suns     1.0       SG  19.0    6-6   206.0   
Stanley Johnson         Detroit Pistons     3.0       SF  20.0    6-7   245.0   
Tyus Jones       Minnesota Timberwolves     1.0       PG  20.0    6-2   195.0   
...                                 ...     ...      ...   ...    ...     ...   
Vince Carter          Memphis Grizzlies    15.0       SG  39.0    6-6   220.0   
Pablo Prigioni     Los Angeles Clippers     9.0       PG  39.0    6-3   185.0   
Tim Duncan            San Antonio Spurs    21.0        C  40.0   6-11   250.0   
Kevin Garnett    Minnesota Timberwolves    21.0       PF  40.0   6-11   240.0   
Andre Miller          San Antonio Spurs    24.0       PG  40.0    6-3   200.0   

                        College     Salary  
Name                                        
NaN                         NaN        NaN  
Rashad Vaughn              UNLV  1733040.0  
Devin Booker           Kentucky  2127840.0  
Stanley Johnson         Arizona  2841960.0  
Tyus Jones                 Duke  1282080.0  
...                         ...        ...  
Vince Carter     North Carolina  4088019.0  
Pablo Prigioni              NaN   947726.0  
Tim Duncan          Wake Forest  5250000.0  
Kevin Garnett               NaN  8500000.0  
Andre Miller               Utah   250750.0  

[458 rows x 8 columns]

In [53]:
df.sort_values('Age',axis=0,ascending=False,inplace =True,na_position='first')
df

Team  Number Position   Age Height  Weight  \
Name                                                                            
NaN                                 NaN     NaN      NaN   NaN    NaN     NaN   
Andre Miller          San Antonio Spurs    24.0       PG  40.0    6-3   200.0   
Kevin Garnett    Minnesota Timberwolves    21.0       PF  40.0   6-11   240.0   
Tim Duncan            San Antonio Spurs    21.0        C  40.0   6-11   250.0   
Pablo Prigioni     Los Angeles Clippers     9.0       PG  39.0    6-3   185.0   
...                                 ...     ...      ...   ...    ...     ...   
Jahlil Okafor        Philadelphia 76ers     8.0        C  20.0   6-11   275.0   
Stanley Johnson         Detroit Pistons     3.0       SF  20.0    6-7   245.0   
Tyus Jones       Minnesota Timberwolves     1.0       PG  20.0    6-2   195.0   
Devin Booker               Phoenix Suns     1.0       SG  19.0    6-6   206.0   
Rashad Vaughn           Milwaukee Bucks    20.0       SG  19.0    6-6   202.0   

                     College     Salary  
Name                                     
NaN                      NaN        NaN  
Andre Miller            Utah   250750.0  
Kevin Garnett            NaN  8500000.0  
Tim Duncan       Wake Forest  5250000.0  
Pablo Prigioni           NaN   947726.0  
...                      ...        ...  
Jahlil Okafor           Duke  4582680.0  
Stanley Johnson      Arizona  2841960.0  
Tyus Jones              Duke  1282080.0  
Devin Booker        Kentucky  2127840.0  
Rashad Vaughn           UNLV  1733040.0  

[458 rows x 8 columns]

In [54]:
data = {'Name':['John','Alice','Bob'],
        'Age':[28,24,22],
        'Salary':[50000,60000,45000]}
data

{'Name': ['John', 'Alice', 'Bob'],
 'Age': [28, 24, 22],
 'Salary': [50000, 60000, 45000]}

In [55]:
data1=pd.DataFrame(data)
data1

Name  Age  Salary
0   John   28   50000
1  Alice   24   60000
2    Bob   22   45000

In [56]:
data1.sort_index(axis=1,ascending=True,inplace =True)
data1

Age   Name  Salary
0   28   John   50000
1   24  Alice   60000
2   22    Bob   45000

# Create a dataframe having 4 columns and 5 entries each sort the data alphabaticaly according to the name columns.Further sort the data set on the basis of Gender column.Arrange the columns in alphabatical order.

In [57]:
df = {'Name':['Siddharth','Swara','Harshyyy','Rishyyy',"Nakul"],
        'Age':[23,22,21,20,19],
        'Gender':["Male","Female","Female","Male","Male"],
        'State':["Bihar","Delhi","Uttar Pardesh","Chennai","Rajasthan"],}
df

{'Name': ['Siddharth', 'Swara', 'Harshyyy', 'Rishyyy', 'Nakul'],
 'Age': [23, 22, 21, 20, 19],
 'Gender': ['Male', 'Female', 'Female', 'Male', 'Male'],
 'State': ['Bihar', 'Delhi', 'Uttar Pardesh', 'Chennai', 'Rajasthan']}

In [58]:
data2 =pd.DataFrame(df)
data2

Name  Age  Gender          State
0  Siddharth   23    Male          Bihar
1      Swara   22  Female          Delhi
2   Harshyyy   21  Female  Uttar Pardesh
3    Rishyyy   20    Male        Chennai
4      Nakul   19    Male      Rajasthan

In [59]:
data2.sort_index(axis=1,ascending=True,inplace =False)

Age  Gender       Name          State
0   23    Male  Siddharth          Bihar
1   22  Female      Swara          Delhi
2   21  Female   Harshyyy  Uttar Pardesh
3   20    Male    Rishyyy        Chennai
4   19    Male      Nakul      Rajasthan

# 05.03.2024

# Create a DataFrame consisting of Name,Age,Gender,Marks 1 and Marks 2.Where in each column contain 5 entries.
#Q1.Sort the Age column in ascending column
#Q2.Sort based on subject 1 in descending order
#Q3.Shift the Gender towards the last of the DataFrame
#Q4.Sort the DataSet alphabetically as per the name column and remove the last row.


In [60]:
df = {'Name':['Siddharth','Swara','Harshyyy','Rishyyy',"Nakul"],
        'Age':[23,22,21,20,19],
        'Gender':["Male","Female","Female","Male","Male"],
        'English':[88,76,66,48,93],
         'Maths':[44,52,88,45,23]}
df

{'Name': ['Siddharth', 'Swara', 'Harshyyy', 'Rishyyy', 'Nakul'],
 'Age': [23, 22, 21, 20, 19],
 'Gender': ['Male', 'Female', 'Female', 'Male', 'Male'],
 'English': [88, 76, 66, 48, 93],
 'Maths': [44, 52, 88, 45, 23]}

In [61]:
data1=pd.DataFrame(df)
data1

Name  Age  Gender  English  Maths
0  Siddharth   23    Male       88     44
1      Swara   22  Female       76     52
2   Harshyyy   21  Female       66     88
3    Rishyyy   20    Male       48     45
4      Nakul   19    Male       93     23

In [62]:
data1.sort_values('Age',axis=0,ascending=True,inplace =False)

Name  Age  Gender  English  Maths
4      Nakul   19    Male       93     23
3    Rishyyy   20    Male       48     45
2   Harshyyy   21  Female       66     88
1      Swara   22  Female       76     52
0  Siddharth   23    Male       88     44

In [63]:
data1.sort_values('Maths',axis=0,ascending=False,inplace =False)

Name  Age  Gender  English  Maths
2   Harshyyy   21  Female       66     88
1      Swara   22  Female       76     52
3    Rishyyy   20    Male       48     45
0  Siddharth   23    Male       88     44
4      Nakul   19    Male       93     23

In [64]:
data1.sort_index(axis=1,ascending=False,inplace=True)
data1

Name  Maths  Gender  English  Age
0  Siddharth     44    Male       88   23
1      Swara     52  Female       76   22
2   Harshyyy     88  Female       66   21
3    Rishyyy     45    Male       48   20
4      Nakul     23    Male       93   19

In [65]:
new_column = data1.columns.tolist()

In [66]:
new_column.remove('Gender')
new_column.append('Gender')

In [67]:
data2 = data1[new_column]

In [68]:
data2

Name  Maths  English  Age  Gender
0  Siddharth     44       88   23    Male
1      Swara     52       76   22  Female
2   Harshyyy     88       66   21  Female
3    Rishyyy     45       48   20    Male
4      Nakul     23       93   19    Male

In [69]:
data1.sort_values('Name',axis=0,ascending=True,inplace =False)

Name  Maths  Gender  English  Age
2   Harshyyy     88  Female       66   21
4      Nakul     23    Male       93   19
3    Rishyyy     45    Male       48   20
0  Siddharth     44    Male       88   23
1      Swara     52  Female       76   22

# 07.03.2024

# Group By Function

In [70]:

data = {'Name':['a','b','c','d','a','b','c','d','a','b','c','d','a','b','c','d'],
      'Marks1':[88,76,66,48,33,64,25,65,3,64,3,65,46,46,3,35],
      'Marks2':[44,52,88,45,33,54,33,64,75,36,35,37,46,5,10,23]}
data

{'Name': ['a',
  'b',
  'c',
  'd',
  'a',
  'b',
  'c',
  'd',
  'a',
  'b',
  'c',
  'd',
  'a',
  'b',
  'c',
  'd'],
 'Marks1': [88, 76, 66, 48, 33, 64, 25, 65, 3, 64, 3, 65, 46, 46, 3, 35],
 'Marks2': [44, 52, 88, 45, 33, 54, 33, 64, 75, 36, 35, 37, 46, 5, 10, 23]}

In [71]:
df =pd.DataFrame(data)
df

Name  Marks1  Marks2
0     a      88      44
1     b      76      52
2     c      66      88
3     d      48      45
4     a      33      33
5     b      64      54
6     c      25      33
7     d      65      64
8     a       3      75
9     b      64      36
10    c       3      35
11    d      65      37
12    a      46      46
13    b      46       5
14    c       3      10
15    d      35      23

In [72]:
new_group= df.groupby('Name')
new_group

In [73]:
for x,y in  new_group:
    print(x)
    print(y)

a
   Name  Marks1  Marks2
0     a      88      44
4     a      33      33
8     a       3      75
12    a      46      46
b
   Name  Marks1  Marks2
1     b      76      52
5     b      64      54
9     b      64      36
13    b      46       5
c
   Name  Marks1  Marks2
2     c      66      88
6     c      25      33
10    c       3      35
14    c       3      10
d
   Name  Marks1  Marks2
3     d      48      45
7     d      65      64
11    d      65      37
15    d      35      23


In [74]:
new_group.mean()

Marks1  Marks2
Name                
a      42.50   49.50
b      62.50   36.75
c      24.25   41.50
d      53.25   42.25

In [75]:
new_group.get_group('a').mean()

C:\Users\Gratitude\AppData\Local\Temp\ipykernel_11872\2382771152.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  new_group.get_group('a').mean()


Marks1    42.5
Marks2    49.5
dtype: float64

In [76]:
#Create a DataFrame containing 10 Names,Age,Salary and Departmnet
#Q1) Filter a DataFrame to show only age onlt gretaer than 25 
#Q2) To show only Rows with salary less than 60k
#Q3) Sort the data in DESC order with respect to salary
#Q4) Sort the data in DESC order with respect to AGE but displaying only the rows with the AGE greater than 55


In [77]:
DataFrame = {'Name':['Siddharth','Swara','Harshyyy','Rishyyy',"Nakul","Khushi","Bharat","Rohan","Shubham","Ronit"],
        'Age':[23,22,21,20,19,22,33,27,24,29],
        'Salary':[30000,50000,100000,34000,39000,60000,55000,45000,18000,7000],
        'Department':["Public Work","Public Health","Industries","Civil Aviation",
                     "Forest","Environment","Science","Housing","Transport","Mines & Geology"]}
DataFrame

{'Name': ['Siddharth',
  'Swara',
  'Harshyyy',
  'Rishyyy',
  'Nakul',
  'Khushi',
  'Bharat',
  'Rohan',
  'Shubham',
  'Ronit'],
 'Age': [23, 22, 21, 20, 19, 22, 33, 27, 24, 29],
 'Salary': [30000,
  50000,
  100000,
  34000,
  39000,
  60000,
  55000,
  45000,
  18000,
  7000],
 'Department': ['Public Work',
  'Public Health',
  'Industries',
  'Civil Aviation',
  'Forest',
  'Environment',
  'Science',
  'Housing',
  'Transport',
  'Mines & Geology']}

In [78]:
data2=pd.DataFrame(DataFrame)
data2

Name  Age  Salary       Department
0  Siddharth   23   30000      Public Work
1      Swara   22   50000    Public Health
2   Harshyyy   21  100000       Industries
3    Rishyyy   20   34000   Civil Aviation
4      Nakul   19   39000           Forest
5     Khushi   22   60000      Environment
6     Bharat   33   55000          Science
7      Rohan   27   45000          Housing
8    Shubham   24   18000        Transport
9      Ronit   29    7000  Mines & Geology

In [79]:
data2[data2['Age']>25]

Name  Age  Salary       Department
6  Bharat   33   55000          Science
7   Rohan   27   45000          Housing
9   Ronit   29    7000  Mines & Geology

In [80]:
data2[data2['Salary']<60000]

Name  Age  Salary       Department
0  Siddharth   23   30000      Public Work
1      Swara   22   50000    Public Health
3    Rishyyy   20   34000   Civil Aviation
4      Nakul   19   39000           Forest
6     Bharat   33   55000          Science
7      Rohan   27   45000          Housing
8    Shubham   24   18000        Transport
9      Ronit   29    7000  Mines & Geology

In [81]:
data2[data2['Department']=="Public Work"]

Name  Age  Salary   Department
0  Siddharth   23   30000  Public Work

In [82]:
data2.sort_values(by="Salary",ascending=False)

Name  Age  Salary       Department
2   Harshyyy   21  100000       Industries
5     Khushi   22   60000      Environment
6     Bharat   33   55000          Science
1      Swara   22   50000    Public Health
7      Rohan   27   45000          Housing
4      Nakul   19   39000           Forest
3    Rishyyy   20   34000   Civil Aviation
0  Siddharth   23   30000      Public Work
8    Shubham   24   18000        Transport
9      Ronit   29    7000  Mines & Geology

In [93]:
sorted_age =data2[data2['Age']>30]
sorted_age

Name  Age  Salary Department
6  Bharat   33   55000    Science

# 26.03.2024

# Create an array containing 4 integer.Access the second element in 2 different ways.

In [94]:
import numpy as np

In [95]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [96]:
arr = np.array([1,2,3,4,5])
print(arr[1])

2


In [97]:
arr = np.array([1,2,3,4,5])
print(arr[-4])

2


# Construct the 2d array.Access the second element of array.

In [98]:
import array 
from array import*

In [99]:
array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [100]:
print(array[0][1])

2


In [101]:
print(array[0:1,1:2])

[[2]]


In [102]:
print(array[0:1,1:3])

[[2 3]]


# Copy & View

In [103]:
a = np.array([1,2,3,4,5])
co = a.copy()
print(a)
print(co)

[1 2 3 4 5]
[1 2 3 4 5]


In [104]:
b = np.array([6,7,8,9,10])
vi = b.view()
print(b)
print(vi)

[ 6  7  8  9 10]
[ 6  7  8  9 10]


# 28.03.2024

# Iterating Over Arrays

In [105]:
import numpy as np

In [106]:
my_array = np.array([9,8,7,6,5,4,3])
print(my_array)

[9 8 7 6 5 4 3]


In [107]:
type(my_array)

numpy.ndarray

In [108]:
for i in my_array:
    print(i)

9
8
7
6
5
4
3


In [109]:
my_array2 = np.array([[20,19,18,17,16,15,14],[13,12,11,10,9,8,7]])
print(my_array2)

[[20 19 18 17 16 15 14]
 [13 12 11 10  9  8  7]]


In [110]:
for i in my_array2:
    for j in i:
        print(j)

20
19
18
17
16
15
14
13
12
11
10
9
8
7


# Joining Arrays :- Order of arrays should be same

In [111]:
my_array3 = np.array([1,2,3,4,5])
my_array3

array([1, 2, 3, 4, 5])

In [112]:
my_array4 = ([6,7,8,9,10])
my_array4

[6, 7, 8, 9, 10]

In [113]:
arr = np.concatenate((my_array3,my_array4),axis=0)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [114]:
arr = np.concatenate((my_array3,my_array4))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [115]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [116]:
arr = np.concatenate((a,b),axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [117]:
arr = np.concatenate((a,b),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# Stack Method

In [118]:
my_array5 = np.array([1,2,3,4,5])
my_array6 = np.array([6,7,8,9,10])
print(my_array5)
print(my_array6)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [119]:
new_arr = np.stack((my_array5,my_array6),axis=0)
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [120]:
new_arr = np.stack((my_array5,my_array6),axis=1)
new_arr

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

# 02.04.2024

In [121]:
#Q1)Create 1D array with integer from 0 to 9
#Q2)Create 2D array with order 2 cross 2 containing random numbers?
#Q3)Perform element wise addition,Substraction,Multiplication and division on the 1D created?
#Q4)Calculate maximum,minimum values and mean of the both the arrays?
#Q5)Access the third element from 1D array?
#Q6)Slice the 2D array to extract the second row?

In [122]:
import numpy as np

In [123]:
#1
my_arr = np.array([0,1,2,3,4,5,6,7,8,9])
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
#2
random = np.random.rand(2,2)
random

array([[0.34446603, 0.23356699],
       [0.12160762, 0.74328468]])

In [125]:
#3
arr =np.array( [1,2,3,4,5])
new_array = (arr + 2)
new_array

array([3, 4, 5, 6, 7])

In [126]:
new_array = (arr - 2)
new_array

array([-1,  0,  1,  2,  3])

In [127]:
new_array = (arr * 2)
new_array

array([ 2,  4,  6,  8, 10])

In [128]:
new_array = (arr / 2)
new_array

array([0.5, 1. , 1.5, 2. , 2.5])

In [129]:
#4
arr1 = np.array([1,2,3,4,5])
random_array=np.min(arr1)
random_array

1

In [130]:
arr1 = np.array([1,2,3,4,5])
random_array=np.max(arr1)
random_array

5

In [131]:
arr1 = np.array([1,2,3,4,5])
random_array=np.mean(arr1)
random_array

3.0

In [132]:
#5
my_arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
new_array1 = my_arr1[3]
new_array1

4

In [133]:
#6
my_arr = np.array([[0,1,2,3,4,5,6,7,8,9],[12,16,17,18,12,13,14,11,16,19]])
my_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [12, 16, 17, 18, 12, 13, 14, 11, 16, 19]])

In [134]:
my_arr[1:]

array([[12, 16, 17, 18, 12, 13, 14, 11, 16, 19]])